<a href="https://colab.research.google.com/github/AdriannMo/E50A-E01/blob/main/ExamenUnidad2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 #### PREGUNTA 2

In [1]:
from google.colab import files
uploaded = files.upload()

Saving items.csv to items.csv

In [4]:
import pandas as pd
import io

# Load the uploaded file into a DataFrame
df = pd.read_csv(io.BytesIO(uploaded['items.csv']))
print("Original DataFrame (df):")
display(df)

# Create the 'importe' column using eval()
df.eval('importe = precio * cantidad', inplace=True)
print("DataFrame after adding 'importe' column:")
display(df)

# Filter for categoria == 'A' using query() and store in dfa
dfa = df.query("categoria == 'A'")
print("Filtered DataFrame (dfa) for categoria == 'A':")
display(dfa)

# Calculate the average of 'importe' per category in the original DataFrame df
average_importe_by_category = df.groupby('categoria')['importe'].mean()
print("Average 'importe' by category (from original DataFrame):")
display(average_importe_by_category)

# Get the average importe for category 'A' and round to 3 decimal places
average_importe_A = round(average_importe_by_category['A'], 3)

print(f"\nEl promedio de importe de la categoría A (en el DataFrame original) es: {average_importe_A}")

Original DataFrame (df):

  categoria item  precio  cantidad
0         A    x     100         2
1         A    y     250         1
2         B    z      80         5
3         B    w     120         3
4         A    k     200         2

DataFrame after adding 'importe' column:

  categoria item  precio  cantidad  importe
0         A    x     100         2      200
1         A    y     250         1      250
2         B    z      80         5      400
3         B    w     120         3      360
4         A    k     200         2      400

Filtered DataFrame (dfa) for categoria == 'A':

  categoria item  precio  cantidad  importe
0         A    x     100         2      200
1         A    y     250         1      250
4         A    k     200         2      400

Average 'importe' by category (from original DataFrame):

categoria
A    283.333333
B    380.000000
Name: importe, dtype: float64

El promedio de importe de la categoría A (en el DataFrame original) es: 283.333

####PREGUNTA 3

In [5]:
from google.colab import files
uploaded = files.upload()

Saving ordenes.csv to ordenes.csv
Saving clientes.csv to clientes.csv

In [6]:
import pandas as pd
import io

# Load ordenes.csv into dfo
dfo = pd.read_csv(io.BytesIO(uploaded['ordenes.csv']))
print("DataFrame de Órdenes (dfo):")
display(dfo)

# Load clientes.csv into dfc
dfc = pd.read_csv(io.BytesIO(uploaded['clientes.csv']))
print("DataFrame de Clientes (dfc):")
display(dfc)

# Perform a left merge of dfc with dfo by cliente_id, keeping all rows of dfc
merged_df = pd.merge(dfc, dfo, on='cliente_id', how='left')
print("DataFrame después del left merge (merged_df):")
display(merged_df)

# (a) Calculate total number of rows of the merged_df
total_rows_merged = len(merged_df)
print(f"\n(a) Número total de filas del resultado del left merge: {total_rows_merged}")

# (b) Calculate total amount per client and replace NaN with 0
monto_total_por_cliente = merged_df.groupby('cliente_id')['monto'].sum().fillna(0)
print("\n(b) Monto total por cliente (NaNs reemplazados por 0):")
display(monto_total_por_cliente)

# Get the total amount for cliente_id=1
monto_cliente_1 = monto_total_por_cliente.loc[1]
print(f"\nEl monto total por cliente con cliente_id=1 es: {monto_cliente_1}")

DataFrame de Órdenes (dfo):

   orden_id  cliente_id  monto
0       101           1    300
1       102           1    150
2       103           3    200
3       104           5    400

DataFrame de Clientes (dfc):

   cliente_id  nombre  segmento
0           1     Ana   Premium
1           2    Luis  Standard
2           3  Camila  Standard
3           4    Jose   Premium

DataFrame después del left merge (merged_df):

   cliente_id  nombre  segmento  orden_id  monto
0           1     Ana   Premium     101.0  300.0
1           1     Ana   Premium     102.0  150.0
2           2    Luis  Standard       NaN    NaN
3           3  Camila  Standard     103.0  200.0
4           4    Jose   Premium       NaN    NaN

(a) Número total de filas del resultado del left merge: 5

(b) Monto total por cliente (NaNs reemplazados por 0):

cliente_id
1    450.0
2      0.0
3    200.0
4      0.0
Name: monto, dtype: float64

El monto total por cliente con cliente_id=1 es: 450.0

#### PREGUNTA 4

In [7]:
from google.colab import files
uploaded = files.upload()

Saving sensores.csv to sensores.csv

In [9]:
import pandas as pd
import io

# Load the uploaded file into a DataFrame
df_sensores = pd.read_csv(io.BytesIO(uploaded['sensores.csv']))
print("Original DataFrame (df_sensores):")
display(df_sensores)

# Convert 'ts' to datetime, handling mixed formats and coercing errors
df_sensores['ts'] = pd.to_datetime(df_sensores['ts'], format='mixed', errors='coerce')
print("DataFrame after converting 'ts' to datetime:")
display(df_sensores)

# Calculate median for 'temperatura' and mean for 'humedad'
median_temperatura = df_sensores['temperatura'].median()
mean_humedad = df_sensores['humedad'].mean()

# Replace missing values
df_sensores['temperatura'].fillna(median_temperatura, inplace=True)
df_sensores['humedad'].fillna(mean_humedad, inplace=True)
print("DataFrame after imputing missing values:")
display(df_sensores)

# (a) Count NaT values remaining in 'ts'
nat_ts_count = df_sensores['ts'].isna().sum()
print(f"\n(a) Número de NaT restantes en 'ts': {nat_ts_count}")

# (b) Final median of 'temperatura' after imputation
final_median_temperatura = round(df_sensores['temperatura'].median(), 1)
print(f"(b) Mediana final de 'temperatura' : {final_median_temperatura}")

# (c) Final mean of 'humedad' after imputation
final_mean_humedad = round(df_sensores['humedad'].mean(), 3)
print(f"(c) Media final de 'humedad' : {final_mean_humedad}")

Original DataFrame (df_sensores):

   id                   ts  temperatura  humedad ubicacion
0  a1     2025-02-01 10:00         23.5     45.2   almacen
1  a2     2025/02/01 10:05          NaN     46.0   almacen
2  a3     01-02-2025 10:10         22.1      NaN   oficina
3  a4  2025-02-01T10:15:00          NaN     47.3   oficina

DataFrame after converting 'ts' to datetime:

   id                  ts  temperatura  humedad ubicacion
0  a1 2025-02-01 10:00:00         23.5     45.2   almacen
1  a2 2025-02-01 10:05:00          NaN     46.0   almacen
2  a3 2025-01-02 10:10:00         22.1      NaN   oficina
3  a4 2025-02-01 10:15:00          NaN     47.3   oficina

DataFrame after imputing missing values:

/tmp/ipykernel_2515/1143661610.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_sensores['temperatura'].fillna(median_temperatura, inplace=True)
/tmp/ipykernel_2515/1143661610.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_sensores['humedad'].fillna(mean_humedad, inplace=True)

   id                  ts  temperatura    humedad ubicacion
0  a1 2025-02-01 10:00:00         23.5  45.200000   almacen
1  a2 2025-02-01 10:05:00         22.8  46.000000   almacen
2  a3 2025-01-02 10:10:00         22.1  46.166667   oficina
3  a4 2025-02-01 10:15:00         22.8  47.300000   oficina

(a) Número de NaT restantes en 'ts': 0
(b) Mediana final de 'temperatura' : 22.8
(c) Media final de 'humedad' : 46.167